### ISSUE TITLE
[feat]insecure-registry

### ISSUE THREAD

**Issue by Desiki-high** [nydusaccelerator/hello-bench#3]
I don't find any args can use the insecure-registry.
When testing in a private registry like harbor, we always need to skip verify, so maybe we can add the arg  --insecure(bool, default false) to use the `nerdctl pull --insecure-registry xxxx` as the pull_cmd when insecure is true. As follows(not done).
<img width="797" alt="image" src="https://user-images.githubusercontent.com/59167816/206443400-0b3c76f1-6e09-432d-a1dc-43c5876c805d.png">

**Comment by Desiki-high** [comment]
And the bench result just output to the txt and cover every time , maybe we can use a excel or db to persistence the result with the timestamp as the primary key

**Comment by sctb512** [comment]
> And the bench result just output to the txt and cover every time , maybe we can use a excel or db to persistence the result with the timestamp as the primary key

It sounds great. Maybe a csv file is sufficient. Otherwise, we can add `timestamp` to json items as raw data and handle them in a python script.

**Comment by sctb512** [comment]
> I don't find any args can use the insecure-registry. When testing in a private registry like harbor, we always need to skip verify, so maybe we can add the arg --insecure(bool, default false) to use the `nerdctl pull --insecure-registry xxxx` as the pull_cmd when insecure is true. As follows(not done). <img alt="image" width="797" src="https://user-images.githubusercontent.com/59167816/206443400-0b3c76f1-6e09-432d-a1dc-43c5876c805d.png">

It is essential. Are you working for this?
